//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.17 at 11:09:07 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.cjet.com/xml/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_cjet_com.xml.payment;
