package com.cjet.demo.model;

public class Payments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz.payments.id
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz.payments.amount
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz.payments.status
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz.payments.method
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    private String method;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz.payments.id
     *
     * @return the value of quartz.payments.id
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz.payments.id
     *
     * @param id the value for quartz.payments.id
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz.payments.amount
     *
     * @return the value of quartz.payments.amount
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz.payments.amount
     *
     * @param amount the value for quartz.payments.amount
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz.payments.status
     *
     * @return the value of quartz.payments.status
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz.payments.status
     *
     * @param status the value for quartz.payments.status
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz.payments.method
     *
     * @return the value of quartz.payments.method
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz.payments.method
     *
     * @param method the value for quartz.payments.method
     *
     * @mbg.generated Sun Nov 17 21:40:22 EST 2019
     */
    public void setMethod(String method) {
        this.method = method;
    }
}